name: Python CI

# This workflow runs for every push or pull request on the “main” or “master” branches
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout of the repository
    - name: Check out the repository
      uses: actions/checkout@v3

    # Step 2: Setup Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Wähle die Python-Version (z.B. 3.8, 3.9, etc.)

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 4: Run tests with pytest
    - name: Run tests
      run: |
        pytest
